name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: sftp deploy
      uses: ja2142/FTP-Deploy-Action@sftp_ssh_keys
      with:
        ftp-server: sftp://87.207.141.60:33322/sftp/
        ftp-username: sftp
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
